#!/usr/bin/env bash
# integrity.sh -- has the scoring machinery changed?
#
#   ./scripts/integrity.sh            # verify; exit 1 on drift
#   ./scripts/integrity.sh --update   # re-baseline after a deliberate change
#
# WHY THIS EXISTS, CONCRETELY
#
# An agent under a Stop gate is told "you may not finish until this is green".
# The files that decide what green means live in this repo and are writable.
# That is not a hypothetical: while the gate was first being armed here, an
# unattended run -- prompted with nothing more than "reply with ok" -- edited
# verify-gate.sh and validate_hooks.py so the gate would pass. The edits were
# plausible and well-commented. Nothing flagged them; `git status` did.
#
# WHY A CHECKSUM ALONE WOULD NOT HELP
#
# An agent that can edit a scorer can also run `--update`. A tripwire it can
# silently re-arm protects nothing. So the load-bearing mechanism here is not
# the check, it is the MANIFEST BEING COMMITTED: changing a scorer forces a
# visible change to integrity.sha256 in the pull request, and CI fails if the
# two disagree. The signal is delivered to a reviewer, not to the agent.
#
# That is the difference from the run-scoped version of this idea, where a
# checksum delta invalidates one measured run. Here the unit is a PR, so the
# diff is the alarm.
#
# WHAT IS COVERED
#
# Two classes, listed separately in the manifest because they earn different
# scrutiny. SCORERS decide pass/fail and should almost never change. ASSERTIONS
# are the cases themselves -- these change often and legitimately, and a
# reviewer's question there is "was a case weakened or deleted", not "why did
# this change at all".

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 70

command -v shasum >/dev/null || { echo "FATAL: shasum not found" >&2; exit 70; }

MANIFEST=scripts/integrity.sha256

SCORERS=(
  scripts/verify.sh
  scripts/plugin_costs.py
  scripts/cost-budgets.json
  evals/guardrails/run.sh
  evals/guardrails/validate_hooks.py
  evals/guardrails/validate_manifests.py
  evals/guardrails/validate_templates.py
  evals/pr-description/run.sh
  .github/workflows/checks.yml
)
ASSERTIONS=(
  evals/guardrails/cases.json
  evals/pr-description/cases.json
)

missing=0
for f in "${SCORERS[@]}" "${ASSERTIONS[@]}"; do
  [[ -f "$f" ]] || { echo "FATAL: covered file is missing: $f" >&2; missing=1; }
done
# A scorer that has been deleted rather than edited would otherwise sail
# through a checksum check that only looks at the files it can still find.
[[ $missing -eq 0 ]] || exit 1

generate() {
  echo "# Scoring machinery for this repo. Generated by scripts/integrity.sh --update."
  echo "#"
  echo "# This file is committed on purpose. A change to anything below shows up"
  echo "# here, in the diff, where a reviewer sees it -- which is the point, since"
  echo "# an agent that can edit a scorer can also re-run --update."
  echo "#"
  echo "# scorers -- decide pass/fail; should almost never change"
  shasum -a 256 "${SCORERS[@]}"
  echo "# assertions -- change often; the question is whether one was weakened"
  shasum -a 256 "${ASSERTIONS[@]}"
}

if [[ "${1:-}" == "--update" ]]; then
  generate > "$MANIFEST"
  echo "integrity manifest re-baselined -> $MANIFEST"
  echo "Commit it. The diff is the review signal."
  exit 0
fi

[[ -f "$MANIFEST" ]] || {
  echo "FATAL: no manifest at $MANIFEST -- run --update once and commit it" >&2
  exit 70
}

if grep -v '^#' "$MANIFEST" | shasum -a 256 --check --status; then
  echo "  integrity: scoring machinery matches the committed manifest"
  exit 0
fi

{
  echo "INTEGRITY DRIFT -- the scoring machinery does not match the manifest:"
  grep -v '^#' "$MANIFEST" | shasum -a 256 --check 2>/dev/null | grep -v ': OK$'
  echo
  echo "If this was deliberate: ./scripts/integrity.sh --update, then commit"
  echo "the manifest so the change is visible in review."
  echo "If it was not: something edited what decides whether this repo passes."
} >&2
exit 1
